---
- hosts: all_splunk
  gather_facts: no
  become: yes
  tasks:
  
    - name: Now updating .bashrc file for all AWS Splunk hosts
      blockinfile:
        path: /home/mpham/.bashrc
        marker_begin: "BEGIN CUSTOM PHAM BASHRC"
        marker_end: "END CUSTOM PHAM BASHRC"
        block: |

         # stop here if this is not an interactive shell (e.g. ssh <hostname> ls)
         [[ $- == *i* ]] || return

         #############################################
         # Custom terminal prompt colors 
         #############################################
         
         black=$(tput setaf 0);
         red=$(tput setaf 1);
         green=$(tput setaf 2);
         yellow=$(tput setaf 3);
         blue=$(tput setaf 4);
         magenta=$(tput setaf 5);
         cyan=$(tput setaf 6);
         white=$(tput setaf 7);
         bold=$(tput bold);
         reset=$(tput sgr0);
         
         PS1="\[${bold}\]\n";
         PS1+="\[${green}\]\u";   # Username
         PS1+="\[${white}\] @ ";
         PS1+="\[${cyan}\]\H";    # Hostname
         PS1+="\[${white}\] in ";
         PS1+="\[${yellow}\]\w ";  # Working directory
         PS1+="\n";
         PS1+="\[${green}\](｡◕‿‿◕｡) \$ \[${reset}\]"; # `$` (and reset color)
         export PS1;
         
         
         alias s2s="sudo su - splunk";
         alias s2r="sudo su - root";
         alias s2a="sudo su - ansible";
         alias lsg="ls -lah | grep -i";
         alias hg="history | grep -i"
         alias e="exit"

         alias ebrc="vim ~/.bashrc";
         alias sbrc="source ~/.bashrc";
         
         echo -e "\e[38;5;36m";
         echo '                                   __                  ';
         echo '   ________  ____  ____     ____  / /_  ____  ____ ___ ';
         echo '  / __ \__ \/ __ \/ __ \   / __ \/ __ \/ __ \/ __ \__ \';
         echo ' / / / / / / /_/ / / / /  / /_/ / / / / /_/ / / / / / /';
         echo '/_/ /_/ /_/\__,_/_/ /_/  / .___/_/ /_/\__,_/_/ /_/ /_/ ';
         echo '                        /_/                            ';
         echo -e "\e[0m";
         
         echo -e "\e[1;4;92mSHORTCUTS\e[0m\n";
         
         echo -e "\e[38;5;36ms2a\e[0m = ${BASH_ALIASES[s2a]}";
         echo -e "\e[38;5;36ms2s\e[0m = ${BASH_ALIASES[s2s]}";
         echo -e "\e[38;5;36ms2r\e[0m = ${BASH_ALIASES[s2r]}";
         echo -e "\e[38;5;36mlsg\e[0m = ${BASH_ALIASES[lsg]}";
         echo -e "\e[38;5;36mhg\e[0m  = ${BASH_ALIASES[hg]}";
         echo -e "\e[38;5;36me\e[0m   = ${BASH_ALIASES[e]}";
         
